# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_predictiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontest',
            name='epochs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictiontest',
            name='minutes_back',
            field=models.IntegerField(default=0),
        ),
    ]
