# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_predictiontest_prediction_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontest',
            name='bias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictiontest',
            name='learningrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictiontest',
            name='momentum',
            field=models.FloatField(default=0),
        ),
    ]
