# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20160222_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontest',
            name='weightdecay',
            field=models.FloatField(default=0),
        ),
    ]
