# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_predictiontest_weightdecay'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontest',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
